//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_H
#define METASPRITE_font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_TILE_ORIGIN 0
#define font_TILE_W 8
#define font_TILE_H 8
#define font_WIDTH 128
#define font_HEIGHT 24
#define font_TILE_COUNT 46
#define font_PALETTE_COUNT 1
#define font_COLORS_PER_PALETTE 4
#define font_TOTAL_COLORS 4

BANKREF_EXTERN(font)

extern const palette_color_t font_palettes[4];
extern const uint8_t font_tiles[736];


#endif
