//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_city_H
#define METASPRITE_city_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define city_TILE_ORIGIN 0
#define city_TILE_W 8
#define city_TILE_H 8
#define city_WIDTH 8
#define city_HEIGHT 8
#define city_TILE_COUNT 4
#define city_PALETTE_COUNT 2
#define city_COLORS_PER_PALETTE 4
#define city_TOTAL_COLORS 8
#define city_PIVOT_X 4
#define city_PIVOT_Y 4
#define city_PIVOT_W 8
#define city_PIVOT_H 8

BANKREF_EXTERN(city)

extern const palette_color_t city_palettes[8];
extern const uint8_t city_tiles[64];

extern const metasprite_t* const city_metasprites[4];

#endif
