//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_linda_H
#define METASPRITE_linda_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define linda_TILE_ORIGIN 0
#define linda_TILE_W 8
#define linda_TILE_H 16
#define linda_WIDTH 32
#define linda_HEIGHT 32
#define linda_TILE_COUNT 162
#define linda_PALETTE_COUNT 2
#define linda_COLORS_PER_PALETTE 4
#define linda_TOTAL_COLORS 8
#define linda_PIVOT_X 16
#define linda_PIVOT_Y 16
#define linda_PIVOT_W 32
#define linda_PIVOT_H 32

BANKREF_EXTERN(linda)

extern const palette_color_t linda_palettes[8];
extern const uint8_t linda_tiles[2592];

extern const metasprite_t* const linda_metasprites[16];

#endif
