//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(enemies)

const palette_color_t enemies_palettes[4] = {
	RGB8(255,255,255), RGB8(170,170,170), RGB8(  0,  0,  0), RGB8( 30,127,  0)
	
};

const uint8_t enemies_tiles[32] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x3c,0x00,0x7e,
	0x00,0xdb,0x00,0xdb,
	0x00,0xff,0x3c,0x00,
	0x1c,0x62,0x00,0x36
	
};

const metasprite_t enemies_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, 0), METASPR_TERM
};

const metasprite_t* const enemies_metasprites[1] = {
	enemies_metasprite0
};
