#ifndef GLOBAL_H
#define GLOBAL_H

#include "graphics/mario.h"
#include "graphics/enemies.h"

#define SPRITE_START_MARIO 0
#define SPRITE_START_ENEMIES SPRITE_START_MARIO + mario_TILE_COUNT

#define TILE_SIZE 8
#define DEVICE_SCREEN_HEIGHT 18
#define DEVICE_SCREEN_WIDTH 20
#define WINDOW_HEIGHT_TILE 2
#define WINDOW_WIDTH_TILE DEVICE_SCREEN_WIDTH
#define WINDOW_SIZE WINDOW_WIDTH_TILE *WINDOW_HEIGHT_TILE
#define WINDOW_X MINWNDPOSX
#define WINDOW_Y MINWNDPOSY

#define TIME_INITIAL_VALUE 400
#define GRAVITY_SPEED 36
#define JUMP_SPEED 25
#define PLAYER_MAX_SPEED_WALK 20
#define PLAYER_MAX_SPEED_RUN 28
#define JUMP_MAX (5 * TILE_SIZE / JUMP_SPEED) << 4
#define LOOP_PER_ANIMATION_FRAME 5
#define MARIO_HALF_WIDTH 4 // TILE_SIZE / 2

#endif
