//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(cursor)

const palette_color_t cursor_palettes[4] = {
	RGB8(255,255,255), RGB8(170,170,170), RGB8( 85, 85, 85), RGB8(  0,  0,  0)
	
};

const uint8_t cursor_tiles[16] = {
	0xc3,0x66,0x81,0xc3,
	0x00,0x81,0x00,0x00,
	0x00,0x00,0x00,0x81,
	0x81,0xc3,0xc3,0x66
	
};

