//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_0_H
#define METASPRITE_image_0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define image_0_TILE_ORIGIN 0
#define image_0_TILE_H 8
#define image_0_WIDTH 160
#define image_0_HEIGHT 144
#define image_0_TILE_COUNT 106
#define image_0_MAP_ATTRIBUTES 0
#define image_0_TILE_PALS image_0_tile_pals

BANKREF_EXTERN(image_0)

extern const palette_color_t image_0_palettes[4];
extern const uint8_t image_0_tiles[1696];

extern const unsigned char image_0_map[360];
extern const unsigned char* image_0_tile_pals[106];

#endif