//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_3_H
#define METASPRITE_image_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define image_3_TILE_ORIGIN 0
#define image_3_TILE_H 8
#define image_3_WIDTH 160
#define image_3_HEIGHT 144
#define image_3_TILE_COUNT 162
#define image_3_MAP_ATTRIBUTES 0
#define image_3_TILE_PALS image_3_tile_pals

BANKREF_EXTERN(image_3)

extern const palette_color_t image_3_palettes[4];
extern const uint8_t image_3_tiles[2592];

extern const unsigned char image_3_map[360];
extern const unsigned char* image_3_tile_pals[162];

#endif