//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_2_H
#define METASPRITE_image_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define image_2_TILE_ORIGIN 0
#define image_2_TILE_H 8
#define image_2_WIDTH 160
#define image_2_HEIGHT 144
#define image_2_TILE_COUNT 125
#define image_2_MAP_ATTRIBUTES 0
#define image_2_TILE_PALS image_2_tile_pals

BANKREF_EXTERN(image_2)

extern const palette_color_t image_2_palettes[4];
extern const uint8_t image_2_tiles[2000];

extern const unsigned char image_2_map[360];
extern const unsigned char* image_2_tile_pals[125];

#endif