//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_cursor_H
#define METASPRITE_cursor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cursor_TILE_ORIGIN 0
#define cursor_TILE_W 8
#define cursor_TILE_H 8
#define cursor_WIDTH 8
#define cursor_HEIGHT 8
#define cursor_TILE_COUNT 1
#define cursor_PALETTE_COUNT 1
#define cursor_COLORS_PER_PALETTE 4
#define cursor_TOTAL_COLORS 4

BANKREF_EXTERN(cursor)

extern const palette_color_t cursor_palettes[4];
extern const uint8_t cursor_tiles[16];


#endif
