//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_World1Tileset_H
#define METASPRITE_World1Tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define World1Tileset_TILE_ORIGIN 0
#define World1Tileset_TILE_W 8
#define World1Tileset_TILE_H 8
#define World1Tileset_WIDTH 224
#define World1Tileset_HEIGHT 8
#define World1Tileset_TILE_COUNT 28
#define World1Tileset_PALETTE_COUNT 2
#define World1Tileset_COLORS_PER_PALETTE 4
#define World1Tileset_TOTAL_COLORS 8

BANKREF_EXTERN(World1Tileset)

extern const palette_color_t World1Tileset_palettes[8];
extern const uint8_t World1Tileset_tiles[448];


#endif
