//AUTOGENERATED FILE FROM png2mtspr
#define city_TILE_H 8
#define city_WIDTH 8
#define city_HEIGHT 8
#define city_PIVOT_X 4
#define city_PIVOT_Y 4

extern const UINT8 city_data[48];
extern const metasprite_t* const city_metasprites[4];
