//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_lindagb_H
#define METASPRITE_lindagb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define lindagb_TILE_ORIGIN 0
#define lindagb_TILE_H 8
#define lindagb_WIDTH 160
#define lindagb_HEIGHT 144
#define lindagb_TILE_COUNT 106
#define lindagb_MAP_ATTRIBUTES 0
#define lindagb_TILE_PALS lindagb_tile_pals

BANKREF_EXTERN(lindagb)

extern const palette_color_t lindagb_palettes[4];
extern const uint8_t lindagb_tiles[1696];

extern const unsigned char lindagb_map[360];
extern const unsigned char* lindagb_tile_pals[106];

#endif