//AUTOGENERATED FILE FROM png2mtspr
#define linda_TILE_H 16
#define linda_WIDTH 16
#define linda_HEIGHT 32
#define linda_PIVOT_X 8
#define linda_PIVOT_Y 16

extern const UINT8 linda_data[640];
extern const metasprite_t* const linda_metasprites[6];
