//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_lindagb_H
#define METASPRITE_lindagb_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define lindagb_TILE_ORIGIN 0
#define lindagb_TILE_W 8
#define lindagb_TILE_H 8
#define lindagb_WIDTH 160
#define lindagb_HEIGHT 144
#define lindagb_TILE_COUNT 106
#define lindagb_PALETTE_COUNT 1
#define lindagb_COLORS_PER_PALETTE 4
#define lindagb_TOTAL_COLORS 4
#define lindagb_MAP_ATTRIBUTES 0

BANKREF_EXTERN(lindagb)

extern const palette_color_t lindagb_palettes[4];
extern const uint8_t lindagb_tiles[1696];

extern const unsigned char lindagb_map[360];

#endif
