//AUTOGENERATED FILE FROM png2mtspr
#define street_TILE_H 8
#define street_WIDTH 8
#define street_HEIGHT 8
#define street_PIVOT_X 4
#define street_PIVOT_Y 4

extern const UINT8 street_data[1984];
extern const metasprite_t* const street_metasprites[256];
