//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_birabuto_H
#define METASPRITE_birabuto_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define birabuto_TILE_ORIGIN 80
#define birabuto_TILE_W 8
#define birabuto_TILE_H 8
#define birabuto_WIDTH 80
#define birabuto_HEIGHT 48
#define birabuto_TILE_COUNT 60
#define birabuto_PALETTE_COUNT 1
#define birabuto_COLORS_PER_PALETTE 4
#define birabuto_TOTAL_COLORS 4

BANKREF_EXTERN(birabuto)

extern const palette_color_t birabuto_palettes[4];
extern const uint8_t birabuto_tiles[960];

#endif
