//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_enemies_H
#define METASPRITE_enemies_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemies_TILE_ORIGIN 0
#define enemies_TILE_W 8
#define enemies_TILE_H 16
#define enemies_WIDTH 16
#define enemies_HEIGHT 16
#define enemies_TILE_COUNT 14
#define enemies_PALETTE_COUNT 1
#define enemies_COLORS_PER_PALETTE 4
#define enemies_TOTAL_COLORS 4
#define enemies_PIVOT_X 8
#define enemies_PIVOT_Y 8
#define enemies_PIVOT_W 16
#define enemies_PIVOT_H 16
extern const metasprite_t* const enemies_metasprites[5];

BANKREF_EXTERN(enemies)

extern const palette_color_t enemies_palettes[4];
extern const uint8_t enemies_tiles[224];

#endif
