//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_muda_H
#define METASPRITE_muda_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define muda_TILE_ORIGIN 80
#define muda_TILE_W 8
#define muda_TILE_H 8
#define muda_WIDTH 80
#define muda_HEIGHT 48
#define muda_TILE_COUNT 60
#define muda_PALETTE_COUNT 1
#define muda_COLORS_PER_PALETTE 4
#define muda_TOTAL_COLORS 4

BANKREF_EXTERN(muda)

extern const palette_color_t muda_palettes[4];
extern const uint8_t muda_tiles[960];

#endif
