//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_text_H
#define METASPRITE_text_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define text_TILE_ORIGIN 0
#define text_TILE_W 8
#define text_TILE_H 8
#define text_WIDTH 80
#define text_HEIGHT 32
#define text_TILE_COUNT 38
#define text_PALETTE_COUNT 1
#define text_COLORS_PER_PALETTE 4
#define text_TOTAL_COLORS 4

BANKREF_EXTERN(text)

extern const palette_color_t text_palettes[4];
extern const uint8_t text_tiles[608];


#endif
