/*

 MAP_002.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : level_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_002Width 20
#define map_002Height 18
#define map_002Bank 0

extern unsigned char map_002[];

/* End of MAP_002.H */
