//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_1_H
#define METASPRITE_image_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define image_1_TILE_ORIGIN 0
#define image_1_TILE_H 8
#define image_1_WIDTH 160
#define image_1_HEIGHT 144
#define image_1_TILE_COUNT 111
#define image_1_MAP_ATTRIBUTES 0
#define image_1_TILE_PALS image_1_tile_pals

BANKREF_EXTERN(image_1)

extern const palette_color_t image_1_palettes[4];
extern const uint8_t image_1_tiles[1776];

extern const unsigned char image_1_map[360];
extern const unsigned char* image_1_tile_pals[111];

#endif