//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_H
#define METASPRITE_image_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define image_TILE_ORIGIN 0
#define image_TILE_H 8
#define image_WIDTH 160
#define image_HEIGHT 144
#define image_TILE_COUNT 181
#define image_MAP_ATTRIBUTES 0
#define image_TILE_PALS image_tile_pals

BANKREF_EXTERN(image)

extern const palette_color_t image_palettes[4];
extern const uint8_t image_tiles[2896];

extern const unsigned char image_map[360];
extern const unsigned char* image_tile_pals[181];

#endif