//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_World1Tileset_H
#define METASPRITE_World1Tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define World1Tileset_TILE_ORIGIN 0
#define World1Tileset_TILE_W 8
#define World1Tileset_TILE_H 8
#define World1Tileset_WIDTH 160
#define World1Tileset_HEIGHT 144
#define World1Tileset_TILE_COUNT 22
#define World1Tileset_PALETTE_COUNT 1
#define World1Tileset_COLORS_PER_PALETTE 4
#define World1Tileset_TOTAL_COLORS 4
#define World1Tileset_MAP_ATTRIBUTES 0

BANKREF_EXTERN(World1Tileset)

extern const palette_color_t World1Tileset_palettes[4];
extern const uint8_t World1Tileset_tiles[352];

extern const unsigned char World1Tileset_map[360];

#endif
