//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_1_2_H
#define METASPRITE_level_1_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1_2_TILE_ORIGIN 40
#define level_1_2_TILE_W 8
#define level_1_2_TILE_H 8
#define level_1_2_WIDTH 2240
#define level_1_2_HEIGHT 128
#define level_1_2_TILE_COUNT 0
#define level_1_2_PALETTE_COUNT 1
#define level_1_2_COLORS_PER_PALETTE 4
#define level_1_2_TOTAL_COLORS 4
#define level_1_2_MAP_ATTRIBUTES 0
extern const unsigned char level_1_2_map[4480];
#define level_1_2_map_attributes level_1_2_map

BANKREF_EXTERN(level_1_2)


#endif
