//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_1_3_H
#define METASPRITE_level_1_3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1_3_TILE_ORIGIN 0
#define level_1_3_TILE_W 8
#define level_1_3_TILE_H 8
#define level_1_3_WIDTH 2560
#define level_1_3_HEIGHT 128
#define level_1_3_TILE_COUNT 50
#define level_1_3_PALETTE_COUNT 1
#define level_1_3_COLORS_PER_PALETTE 4
#define level_1_3_TOTAL_COLORS 4
#define level_1_3_MAP_ATTRIBUTES 0

BANKREF_EXTERN(level_1_3)

extern const palette_color_t level_1_3_palettes[4];
extern const uint8_t level_1_3_tiles[800];

extern const unsigned char level_1_3_map[5120];

#endif
