//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_2_1_H
#define METASPRITE_level_2_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_2_1_TILE_ORIGIN 40
#define level_2_1_TILE_W 8
#define level_2_1_TILE_H 8
#define level_2_1_WIDTH 2560
#define level_2_1_HEIGHT 144
#define level_2_1_TILE_COUNT 85
#define level_2_1_PALETTE_COUNT 3
#define level_2_1_COLORS_PER_PALETTE 4
#define level_2_1_TOTAL_COLORS 12
#define level_2_1_MAP_ATTRIBUTES 0
extern const unsigned char level_2_1_map[5760];
#define level_2_1_map_attributes level_2_1_map

BANKREF_EXTERN(level_2_1)

extern const palette_color_t level_2_1_palettes[8];
extern const uint8_t level_2_1_tiles[1360];

#endif
