//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_1_1_H
#define METASPRITE_level_1_1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_1_1_TILE_ORIGIN 36
#define level_1_1_TILE_W 8
#define level_1_1_TILE_H 8
#define level_1_1_WIDTH 2400
#define level_1_1_HEIGHT 128
#define level_1_1_TILE_COUNT 41
#define level_1_1_PALETTE_COUNT 1
#define level_1_1_COLORS_PER_PALETTE 4
#define level_1_1_TOTAL_COLORS 4
#define level_1_1_MAP_ATTRIBUTES 0

BANKREF_EXTERN(level_1_1)

extern const palette_color_t level_1_1_palettes[4];
extern const uint8_t level_1_1_tiles[656];

extern const unsigned char level_1_1_map[4800];

#endif
